apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-clustersecretstore
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: "http://192.168.49.2:30949"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token-secret
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: aHZzLmJGTHhYZG9TYlloNVM1UnFhTmtKTjdTNg==