apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: mensaje
      remoteRef:
        key: kv/mensaje
        property: mensaje